/* ============================================================
   DATOS DEL CATÁLOGO
   Todas las cartas viven aquí. El HTML ya no tiene productos:
   las páginas los dibujan a partir de este arreglo.
   ============================================================ */

const TIPOS = [
  { id: "fuego", nombre: "Fuego", emoji: "🔥" },
  { id: "agua", nombre: "Agua", emoji: "💧" },
  { id: "planta", nombre: "Planta", emoji: "🌿" },
  { id: "electrico", nombre: "Eléctrico", emoji: "⚡" },
  { id: "psiquico", nombre: "Psíquico", emoji: "🔮" },
  { id: "lucha", nombre: "Lucha", emoji: "🥊" },
  { id: "normal", nombre: "Normal", emoji: "⚪" },
];

// De menor a mayor valor
const RAREZAS = ["Común", "Poco común", "Rara", "Holográfica"];

const CARTAS = [
  {
    id: "charizard",
    nombre: "Charizard",
    tipo: "fuego",
    rareza: "Holográfica",
    numero: 4,
    precio: 89990,
    descuento: 10,
    stock: 3,
    valoracion: 4.9,
    resenas: 214,
    destacada: true,
    imagen: "https://images.pokemontcg.io/base1/4.png",
    descripcion:
      "La carta más buscada del Set Base. Su ataque Llamarada define partidas completas.",
  },
  {
    id: "blastoise",
    nombre: "Blastoise",
    tipo: "agua",
    rareza: "Holográfica",
    numero: 2,
    precio: 84990,
    descuento: 15,
    stock: 4,
    valoracion: 4.9,
    resenas: 168,
    destacada: true,
    imagen: "https://images.pokemontcg.io/base1/2.png",
    descripcion:
      "Hidrobomba y una defensa altísima. Un clásico para cualquier mazo de agua.",
  },
  {
    id: "venusaur",
    nombre: "Venusaur",
    tipo: "planta",
    rareza: "Holográfica",
    numero: 15,
    precio: 72990,
    descuento: 20,
    stock: 5,
    valoracion: 4.8,
    resenas: 141,
    destacada: true,
    imagen: "https://images.pokemontcg.io/base1/15.png",
    descripcion:
      "Su poder Energía Trans permite mover energía entre tus Pokémon cada turno.",
  },
  {
    id: "alakazam",
    nombre: "Alakazam",
    tipo: "psiquico",
    rareza: "Holográfica",
    numero: 1,
    precio: 78990,
    descuento: 0,
    stock: 3,
    valoracion: 4.9,
    resenas: 122,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/1.png",
    descripcion:
      "Cambio de Daño reparte el daño recibido entre toda tu banca. Puro control.",
  },
  {
    id: "mewtwo",
    nombre: "Mewtwo",
    tipo: "psiquico",
    rareza: "Holográfica",
    numero: 10,
    precio: 61990,
    descuento: 15,
    stock: 6,
    valoracion: 4.9,
    resenas: 197,
    destacada: true,
    imagen: "https://images.pokemontcg.io/base1/10.png",
    descripcion:
      "Barrera lo vuelve casi intocable mientras tengas energía psíquica de sobra.",
  },
  {
    id: "zapdos",
    nombre: "Zapdos",
    tipo: "electrico",
    rareza: "Holográfica",
    numero: 16,
    precio: 55990,
    descuento: 0,
    stock: 4,
    valoracion: 4.7,
    resenas: 96,
    destacada: true,
    imagen: "https://images.pokemontcg.io/base1/16.png",
    descripcion:
      "Trueno con 60 de daño directo. Uno de los legendarios más jugados del 99.",
  },
  {
    id: "gyarados",
    nombre: "Gyarados",
    tipo: "agua",
    rareza: "Holográfica",
    numero: 6,
    precio: 52990,
    descuento: 20,
    stock: 5,
    valoracion: 4.8,
    resenas: 133,
    destacada: true,
    imagen: "https://images.pokemontcg.io/base1/6.png",
    descripcion:
      "Furia Dragón golpea con 50 fijos, sin tiradas de moneda de por medio.",
  },
  {
    id: "raichu",
    nombre: "Raichu",
    tipo: "electrico",
    rareza: "Holográfica",
    numero: 14,
    precio: 47990,
    descuento: 10,
    stock: 7,
    valoracion: 4.6,
    resenas: 118,
    destacada: true,
    imagen: "https://images.pokemontcg.io/base1/14.png",
    descripcion:
      "La evolución de Pikachu con Trueno Gigante, capaz de cerrar partidas rápido.",
  },
  {
    id: "chansey",
    nombre: "Chansey",
    tipo: "normal",
    rareza: "Holográfica",
    numero: 3,
    precio: 46990,
    descuento: 0,
    stock: 4,
    valoracion: 4.5,
    resenas: 74,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/3.png",
    descripcion:
      "120 puntos de vida y Muro de Huevos: la muralla defensiva del Set Base.",
  },
  {
    id: "ninetales",
    nombre: "Ninetales",
    tipo: "fuego",
    rareza: "Holográfica",
    numero: 12,
    precio: 44990,
    descuento: 0,
    stock: 6,
    valoracion: 4.6,
    resenas: 88,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/12.png",
    descripcion:
      "Provocar obliga al rival a cambiar de Pokémon activo. Ilustración icónica.",
  },
  {
    id: "clefairy",
    nombre: "Clefairy",
    tipo: "normal",
    rareza: "Holográfica",
    numero: 5,
    precio: 41990,
    descuento: 0,
    stock: 5,
    valoracion: 4.4,
    resenas: 61,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/5.png",
    descripcion:
      "Metrónomo copia los ataques del rival. Impredecible y muy divertida de jugar.",
  },
  {
    id: "hitmonchan",
    nombre: "Hitmonchan",
    tipo: "lucha",
    rareza: "Holográfica",
    numero: 7,
    precio: 38990,
    descuento: 0,
    stock: 6,
    valoracion: 4.5,
    resenas: 79,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/7.png",
    descripcion:
      "Puño Especial atraviesa resistencias. Base de los mazos Haymaker clásicos.",
  },
  {
    id: "nidoking",
    nombre: "Nidoking",
    tipo: "planta",
    rareza: "Holográfica",
    numero: 11,
    precio: 37990,
    descuento: 0,
    stock: 5,
    valoracion: 4.5,
    resenas: 67,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/11.png",
    descripcion:
      "Cuerno Tóxico envenena al contacto y suma daño turno tras turno.",
  },
  {
    id: "machamp",
    nombre: "Machamp",
    tipo: "lucha",
    rareza: "Holográfica",
    numero: 8,
    precio: 35990,
    descuento: 0,
    stock: 8,
    valoracion: 4.4,
    resenas: 92,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/8.png",
    descripcion:
      "Sismo con 60 de daño y su poder Contraataque. Fuerza bruta en estado puro.",
  },
  {
    id: "poliwrath",
    nombre: "Poliwrath",
    tipo: "agua",
    rareza: "Holográfica",
    numero: 13,
    precio: 34990,
    descuento: 0,
    stock: 7,
    valoracion: 4.3,
    resenas: 54,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/13.png",
    descripcion:
      "Ola de Agua escala con la energía que acumules. Paciencia recompensada.",
  },
  {
    id: "magneton",
    nombre: "Magneton",
    tipo: "electrico",
    rareza: "Holográfica",
    numero: 9,
    precio: 33990,
    descuento: 0,
    stock: 6,
    valoracion: 4.4,
    resenas: 58,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/9.png",
    descripcion:
      "Autodestrucción arrasa con el campo completo, incluido el suyo propio.",
  },
  {
    id: "arcanine",
    nombre: "Arcanine",
    tipo: "fuego",
    rareza: "Rara",
    numero: 23,
    precio: 27990,
    descuento: 15,
    stock: 10,
    valoracion: 4.7,
    resenas: 103,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/23.png",
    descripcion:
      "Llamarada a cambio de descartar energía. Una de las ilustraciones favoritas.",
  },
  {
    id: "dragonair",
    nombre: "Dragonair",
    tipo: "normal",
    rareza: "Rara",
    numero: 18,
    precio: 24990,
    descuento: 0,
    stock: 9,
    valoracion: 4.6,
    resenas: 81,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/18.png",
    descripcion:
      "Cola de Escape la devuelve a tu mano para reutilizar sus ataques.",
  },
  {
    id: "charmeleon",
    nombre: "Charmeleon",
    tipo: "fuego",
    rareza: "Rara",
    numero: 24,
    precio: 22990,
    descuento: 0,
    stock: 12,
    valoracion: 4.4,
    resenas: 76,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/24.png",
    descripcion: "El paso obligado hacia Charizard. Garra Ardiente pega fuerte.",
  },
  {
    id: "haunter",
    nombre: "Haunter",
    tipo: "psiquico",
    rareza: "Rara",
    numero: 29,
    precio: 21990,
    descuento: 0,
    stock: 11,
    valoracion: 4.5,
    resenas: 69,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/29.png",
    descripcion: "Hipnosis deja dormido al rival y prepara el golpe de gracia.",
  },
  {
    id: "dratini",
    nombre: "Dratini",
    tipo: "normal",
    rareza: "Rara",
    numero: 26,
    precio: 19990,
    descuento: 0,
    stock: 14,
    valoracion: 4.4,
    resenas: 57,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/26.png",
    descripcion: "La forma base del linaje Dragonite, difícil de conseguir limpia.",
  },
  {
    id: "electabuzz",
    nombre: "Electabuzz",
    tipo: "electrico",
    rareza: "Rara",
    numero: 20,
    precio: 18990,
    descuento: 0,
    stock: 13,
    valoracion: 4.3,
    resenas: 64,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/20.png",
    descripcion: "Puñetazo Trueno barato y constante. Un pilar de los mazos rápidos.",
  },
  {
    id: "ivysaur",
    nombre: "Ivysaur",
    tipo: "planta",
    rareza: "Rara",
    numero: 30,
    precio: 17990,
    descuento: 0,
    stock: 15,
    valoracion: 4.3,
    resenas: 48,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/30.png",
    descripcion: "Látigo Cepa y Somnífero: control y daño en la etapa intermedia.",
  },
  {
    id: "kadabra",
    nombre: "Kadabra",
    tipo: "psiquico",
    rareza: "Rara",
    numero: 32,
    precio: 16990,
    descuento: 0,
    stock: 12,
    valoracion: 4.2,
    resenas: 44,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/32.png",
    descripcion: "Recuperación cura todo el daño a cambio de descartar una energía.",
  },
  {
    id: "dugtrio",
    nombre: "Dugtrio",
    tipo: "lucha",
    rareza: "Rara",
    numero: 19,
    precio: 16490,
    descuento: 0,
    stock: 10,
    valoracion: 4.2,
    resenas: 39,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/19.png",
    descripcion: "Terremoto castiga también a tu propia banca. Alto riesgo, alto daño.",
  },
  {
    id: "beedrill",
    nombre: "Beedrill",
    tipo: "planta",
    rareza: "Rara",
    numero: 17,
    precio: 15990,
    descuento: 0,
    stock: 16,
    valoracion: 4.1,
    resenas: 52,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/17.png",
    descripcion: "Doble Aguijón envenena y golpea dos veces si tienes suerte.",
  },
  {
    id: "jynx",
    nombre: "Jynx",
    tipo: "psiquico",
    rareza: "Rara",
    numero: 31,
    precio: 14990,
    descuento: 0,
    stock: 13,
    valoracion: 4.2,
    resenas: 41,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/31.png",
    descripcion: "Beso Amoroso confunde al rival y arruina su siguiente turno.",
  },
  {
    id: "pidgeotto",
    nombre: "Pidgeotto",
    tipo: "normal",
    rareza: "Rara",
    numero: 22,
    precio: 13990,
    descuento: 0,
    stock: 18,
    valoracion: 4.1,
    resenas: 36,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/22.png",
    descripcion: "Espejismo te deja elegir qué Pokémon del rival recibe el daño.",
  },
  {
    id: "pikachu",
    nombre: "Pikachu",
    tipo: "electrico",
    rareza: "Común",
    numero: 58,
    precio: 12990,
    descuento: 20,
    stock: 26,
    valoracion: 5,
    resenas: 312,
    destacada: true,
    imagen: "https://images.pokemontcg.io/base1/58.png",
    descripcion:
      "La carta más reconocible de la franquicia. Impecable en cualquier colección.",
  },
  {
    id: "growlithe",
    nombre: "Growlithe",
    tipo: "fuego",
    rareza: "Rara",
    numero: 28,
    precio: 12490,
    descuento: 0,
    stock: 17,
    valoracion: 4.3,
    resenas: 45,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/28.png",
    descripcion: "Mordisco simple y barato mientras esperas evolucionar a Arcanine.",
  },
  {
    id: "porygon",
    nombre: "Porygon",
    tipo: "normal",
    rareza: "Poco común",
    numero: 39,
    precio: 11990,
    descuento: 0,
    stock: 15,
    valoracion: 4,
    resenas: 33,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/39.png",
    descripcion: "Conversión cambia su propia debilidad. Rareza técnica muy buscada.",
  },
  {
    id: "wartortle",
    nombre: "Wartortle",
    tipo: "agua",
    rareza: "Poco común",
    numero: 42,
    precio: 10990,
    descuento: 0,
    stock: 19,
    valoracion: 4.3,
    resenas: 58,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/42.png",
    descripcion: "Mordisco y Retirada: el puente natural hacia Blastoise.",
  },
  {
    id: "magikarp",
    nombre: "Magikarp",
    tipo: "agua",
    rareza: "Poco común",
    numero: 35,
    precio: 9990,
    descuento: 0,
    stock: 22,
    valoracion: 4.5,
    resenas: 87,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/35.png",
    descripcion: "Inútil en combate, imprescindible en la colección. Pura nostalgia.",
  },
  {
    id: "machoke",
    nombre: "Machoke",
    tipo: "lucha",
    rareza: "Poco común",
    numero: 34,
    precio: 8990,
    descuento: 0,
    stock: 20,
    valoracion: 4.1,
    resenas: 29,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/34.png",
    descripcion: "Karate Chop escala según el daño que ya haya recibido.",
  },
  {
    id: "magmar",
    nombre: "Magmar",
    tipo: "fuego",
    rareza: "Poco común",
    numero: 36,
    precio: 8490,
    descuento: 0,
    stock: 18,
    valoracion: 4.2,
    resenas: 31,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/36.png",
    descripcion: "Puño Fuego quema al rival y mantiene la presión cada turno.",
  },
  {
    id: "charmander",
    nombre: "Charmander",
    tipo: "fuego",
    rareza: "Común",
    numero: 46,
    precio: 7990,
    descuento: 15,
    stock: 25,
    valoracion: 4.8,
    resenas: 176,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/46.png",
    descripcion: "El inicial más querido. Primer paso de la línea hacia Charizard.",
  },
  {
    id: "nidorino",
    nombre: "Nidorino",
    tipo: "planta",
    rareza: "Poco común",
    numero: 37,
    precio: 6990,
    descuento: 0,
    stock: 24,
    valoracion: 4,
    resenas: 22,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/37.png",
    descripcion: "Doble Patada con moneda: puede llegar a 60 puntos de daño.",
  },
  {
    id: "squirtle",
    nombre: "Squirtle",
    tipo: "agua",
    rareza: "Común",
    numero: 63,
    precio: 5990,
    descuento: 10,
    stock: 28,
    valoracion: 4.7,
    resenas: 149,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/63.png",
    descripcion: "Burbuja paraliza con suerte. Inicial de agua por excelencia.",
  },
  {
    id: "bulbasaur",
    nombre: "Bulbasaur",
    tipo: "planta",
    rareza: "Común",
    numero: 44,
    precio: 5490,
    descuento: 10,
    stock: 30,
    valoracion: 4.7,
    resenas: 152,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/44.png",
    descripcion: "Látigo Cepa por dos energías. El nº 001 de toda la Pokédex.",
  },
  {
    id: "onix",
    nombre: "Onix",
    tipo: "lucha",
    rareza: "Común",
    numero: 56,
    precio: 4990,
    descuento: 0,
    stock: 21,
    valoracion: 4.2,
    resenas: 38,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/56.png",
    descripcion: "Endurecer lo vuelve un muro incómodo de derribar a bajo costo.",
  },
  {
    id: "gastly",
    nombre: "Gastly",
    tipo: "psiquico",
    rareza: "Común",
    numero: 50,
    precio: 4490,
    descuento: 0,
    stock: 23,
    valoracion: 4.3,
    resenas: 42,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/50.png",
    descripcion: "Beso Mortal duerme al rival sin gastar una sola energía.",
  },
  {
    id: "abra",
    nombre: "Abra",
    tipo: "psiquico",
    rareza: "Común",
    numero: 43,
    precio: 4290,
    descuento: 0,
    stock: 24,
    valoracion: 4,
    resenas: 27,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/43.png",
    descripcion: "Psíquico temprano y barato para preparar la línea de Alakazam.",
  },
  {
    id: "ponyta",
    nombre: "Ponyta",
    tipo: "fuego",
    rareza: "Común",
    numero: 60,
    precio: 3990,
    descuento: 0,
    stock: 26,
    valoracion: 4.2,
    resenas: 34,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/60.png",
    descripcion: "Ascuas constante y retirada barata. Muy cómoda de rotar.",
  },
  {
    id: "vulpix",
    nombre: "Vulpix",
    tipo: "fuego",
    rareza: "Común",
    numero: 68,
    precio: 3490,
    descuento: 0,
    stock: 27,
    valoracion: 4.3,
    resenas: 46,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/68.png",
    descripcion: "Confundir con moneda. Ilustración muy apreciada por coleccionistas.",
  },
  {
    id: "magnemite",
    nombre: "Magnemite",
    tipo: "electrico",
    rareza: "Común",
    numero: 53,
    precio: 3290,
    descuento: 0,
    stock: 29,
    valoracion: 4,
    resenas: 25,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/53.png",
    descripcion: "Ondas de Choque paralizan y frenan el ritmo del rival.",
  },
  {
    id: "machop",
    nombre: "Machop",
    tipo: "lucha",
    rareza: "Común",
    numero: 52,
    precio: 3190,
    descuento: 0,
    stock: 25,
    valoracion: 4,
    resenas: 21,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/52.png",
    descripcion: "Golpe Bajo por una sola energía. Arranque agresivo y económico.",
  },
  {
    id: "caterpie",
    nombre: "Caterpie",
    tipo: "planta",
    rareza: "Común",
    numero: 45,
    precio: 2990,
    descuento: 0,
    stock: 32,
    valoracion: 4,
    resenas: 19,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/45.png",
    descripcion: "Disparo Demora. La entrada más barata a la línea de Butterfree.",
  },
  {
    id: "sandshrew",
    nombre: "Sandshrew",
    tipo: "lucha",
    rareza: "Común",
    numero: 62,
    precio: 2890,
    descuento: 0,
    stock: 30,
    valoracion: 3.9,
    resenas: 17,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/62.png",
    descripcion: "Ataque Arena reduce la precisión del rival en el siguiente turno.",
  },
  {
    id: "staryu",
    nombre: "Staryu",
    tipo: "agua",
    rareza: "Común",
    numero: 65,
    precio: 2790,
    descuento: 0,
    stock: 28,
    valoracion: 4,
    resenas: 23,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/65.png",
    descripcion: "Placaje Rápido sencillo mientras preparas la evolución a Starmie.",
  },
  {
    id: "voltorb",
    nombre: "Voltorb",
    tipo: "electrico",
    rareza: "Común",
    numero: 67,
    precio: 2690,
    descuento: 0,
    stock: 26,
    valoracion: 3.9,
    resenas: 15,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/67.png",
    descripcion: "Placaje básico y retirada gratis. Perfecta para rellenar la banca.",
  },
  {
    id: "pidgey",
    nombre: "Pidgey",
    tipo: "normal",
    rareza: "Común",
    numero: 57,
    precio: 2490,
    descuento: 0,
    stock: 34,
    valoracion: 3.9,
    resenas: 18,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/57.png",
    descripcion: "Remolino obliga al rival a descartar una energía. Molesta y barata.",
  },
  {
    id: "rattata",
    nombre: "Rattata",
    tipo: "normal",
    rareza: "Común",
    numero: 61,
    precio: 2390,
    descuento: 0,
    stock: 33,
    valoracion: 3.8,
    resenas: 14,
    destacada: false,
    imagen: "https://images.pokemontcg.io/base1/61.png",
    descripcion: "Mordisco por una energía incolora. La opción más económica del set.",
  },
];

/* ---------- Utilidades de precio ---------- */

// Precio con el descuento ya aplicado
function precioFinal(carta) {
  if (!carta.descuento) {
    return carta.precio;
  }
  return Math.round((carta.precio * (100 - carta.descuento)) / 100 / 10) * 10;
}

// 12990 -> "$12.990"
function formatoPrecio(valor) {
  return "$" + valor.toLocaleString("es-CL");
}

function buscarCarta(id) {
  return CARTAS.find((carta) => carta.id === id);
}

function buscarTipo(id) {
  return TIPOS.find((tipo) => tipo.id === id);
}

// Cuántas cartas hay de cada tipo, para los contadores de los filtros
function contarPorTipo() {
  const conteo = {};
  for (const carta of CARTAS) {
    conteo[carta.tipo] = (conteo[carta.tipo] || 0) + 1;
  }
  return conteo;
}

function contarPorRareza() {
  const conteo = {};
  for (const carta of CARTAS) {
    conteo[carta.rareza] = (conteo[carta.rareza] || 0) + 1;
  }
  return conteo;
}

// Imagen que se usa si el servidor externo no responde
const IMAGEN_RESPALDO =
  "data:image/svg+xml;utf8," +
  encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 250 350">
      <rect width="250" height="350" rx="16" fill="#dfe3ee"/>
      <circle cx="125" cy="168" r="52" fill="none" stroke="#a8b0c6" stroke-width="8"/>
      <path d="M73 168h104" stroke="#a8b0c6" stroke-width="8"/>
      <circle cx="125" cy="168" r="17" fill="#dfe3ee" stroke="#a8b0c6" stroke-width="8"/>
      <text x="125" y="272" text-anchor="middle" font-family="sans-serif"
        font-size="15" fill="#a8b0c6">Imagen no disponible</text>
    </svg>`
  );
