/**
 * Catálogo de productos de PokéStore.
 * Cada producto es un objeto simple con los datos que necesita la tienda.
 * Esta es la única lista de productos: todas las páginas la leen desde aquí,
 * así no hay que repetir las cartas en cada archivo HTML.
 */

const productos = [
  // ---------- FUEGO ----------
  {
    id: 1,
    nombre: "Charmander",
    tipo: "fuego",
    precio: 9000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png",
    descripcion: "Pokémon inicial de tipo fuego. La llama de su cola indica su estado de salud.",
    stock: 15,
    stockCritico: 4,
    destacada: false,
  },
  {
    id: 2,
    nombre: "Charmeleon",
    tipo: "fuego",
    precio: 14000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png",
    descripcion: "Evolución de Charmander. Es agresivo y su cola arde con más intensidad.",
    stock: 10,
    stockCritico: 3,
    destacada: false,
  },
  {
    id: 3,
    nombre: "Charizard",
    tipo: "fuego",
    precio: 65990,
    precioAnterior: 75990,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png",
    descripcion: "Una de las cartas más buscadas por los coleccionistas. Escupe fuego a más de 1500°C.",
    stock: 4,
    stockCritico: 2,
    destacada: true,
  },
  {
    id: 4,
    nombre: "Vulpix",
    tipo: "fuego",
    precio: 5000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/37.png",
    descripcion: "Nace con una sola cola, que se divide en seis a medida que crece.",
    stock: 20,
    stockCritico: 5,
    destacada: false,
  },
  {
    id: 5,
    nombre: "Growlithe",
    tipo: "fuego",
    precio: 7000,
    precioAnterior: 7800,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/58.png",
    descripcion: "Muy leal con su entrenador. Ladra para advertir de cualquier peligro.",
    stock: 12,
    stockCritico: 4,
    destacada: false,
  },
  {
    id: 6,
    nombre: "Arcanine",
    tipo: "fuego",
    precio: 32000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png",
    descripcion: "Corre con elegancia y puede recorrer 10.000 km en un día.",
    stock: 6,
    stockCritico: 2,
    destacada: false,
  },

  // ---------- AGUA ----------
  {
    id: 7,
    nombre: "Squirtle",
    tipo: "agua",
    precio: 8000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png",
    descripcion: "Pokémon inicial de tipo agua. Se protege escondiéndose en su caparazón.",
    stock: 18,
    stockCritico: 5,
    destacada: false,
  },
  {
    id: 8,
    nombre: "Wartortle",
    tipo: "agua",
    precio: 13000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png",
    descripcion: "Su cola peluda es símbolo de longevidad entre los coleccionistas.",
    stock: 9,
    stockCritico: 3,
    destacada: false,
  },
  {
    id: 9,
    nombre: "Blastoise",
    tipo: "agua",
    precio: 35000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png",
    descripcion: "Dispara agua a presión desde los cañones de su caparazón.",
    stock: 5,
    stockCritico: 2,
    destacada: true,
  },
  {
    id: 10,
    nombre: "Psyduck",
    tipo: "agua",
    precio: 6000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png",
    descripcion: "Siempre parece confundido, pero su dolor de cabeza esconde un gran poder psíquico.",
    stock: 14,
    stockCritico: 4,
    destacada: false,
  },
  {
    id: 11,
    nombre: "Poliwag",
    tipo: "agua",
    precio: 5000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/60.png",
    descripcion: "Su piel es tan fina que se puede ver el remolino de su estómago.",
    stock: 16,
    stockCritico: 5,
    destacada: false,
  },
  {
    id: 12,
    nombre: "Lapras",
    tipo: "agua",
    precio: 42000,
    precioAnterior: 48000,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png",
    descripcion: "Un Pokémon gentil que lleva gente en su espalda a través del mar.",
    stock: 3,
    stockCritico: 1,
    destacada: true,
  },

  // ---------- PLANTA ----------
  {
    id: 13,
    nombre: "Bulbasaur",
    tipo: "planta",
    precio: 8000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png",
    descripcion: "Lleva una semilla en el lomo desde que nace. Crece junto con el Pokémon.",
    stock: 17,
    stockCritico: 5,
    destacada: false,
  },
  {
    id: 14,
    nombre: "Ivysaur",
    tipo: "planta",
    precio: 13500,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png",
    descripcion: "Cuando el capullo de su lomo empieza a oler dulce, está a punto de florecer.",
    stock: 9,
    stockCritico: 3,
    destacada: false,
  },
  {
    id: 15,
    nombre: "Venusaur",
    tipo: "planta",
    precio: 44792,
    precioAnterior: 55990,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png",
    descripcion: "La flor de su lomo capta la luz del sol y libera un aroma relajante.",
    stock: 5,
    stockCritico: 2,
    destacada: true,
  },
  {
    id: 16,
    nombre: "Oddish",
    tipo: "planta",
    precio: 4000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/43.png",
    descripcion: "De día se entierra en el suelo y de noche camina buscando luz de luna.",
    stock: 20,
    stockCritico: 6,
    destacada: false,
  },
  {
    id: 17,
    nombre: "Bellsprout",
    tipo: "planta",
    precio: 4500,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/69.png",
    descripcion: "Le encanta el barro húmedo, con más nutrientes para su cuerpo.",
    stock: 18,
    stockCritico: 5,
    destacada: false,
  },

  // ---------- ELÉCTRICO ----------
  {
    id: 18,
    nombre: "Pikachu",
    tipo: "electrico",
    precio: 15000,
    precioAnterior: 18000,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png",
    descripcion: "La carta más pedida de la tienda. Guarda electricidad en sus mejillas.",
    stock: 22,
    stockCritico: 6,
    destacada: true,
  },
  {
    id: 19,
    nombre: "Raichu",
    tipo: "electrico",
    precio: 18000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png",
    descripcion: "Su larga cola actúa como pararrayos, liberando el exceso de electricidad.",
    stock: 11,
    stockCritico: 3,
    destacada: false,
  },
  {
    id: 20,
    nombre: "Magnemite",
    tipo: "electrico",
    precio: 5000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png",
    descripcion: "Se alimenta de electricidad, por lo que suele acercarse a cables de alta tensión.",
    stock: 13,
    stockCritico: 4,
    destacada: false,
  },
  {
    id: 21,
    nombre: "Voltorb",
    tipo: "electrico",
    precio: 4500,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/100.png",
    descripcion: "Se descubrió cuando confundieron una Poké Ball con este Pokémon.",
    stock: 15,
    stockCritico: 4,
    destacada: false,
  },
  {
    id: 22,
    nombre: "Electabuzz",
    tipo: "electrico",
    precio: 21000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/125.png",
    descripcion: "Suele aparecer cerca de centrales eléctricas durante las tormentas.",
    stock: 7,
    stockCritico: 2,
    destacada: false,
  },

  // ---------- PSÍQUICO ----------
  {
    id: 23,
    nombre: "Abra",
    tipo: "psiquico",
    precio: 6000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png",
    descripcion: "Duerme 18 horas al día. Se teletransporta al sentir peligro, incluso dormido.",
    stock: 16,
    stockCritico: 5,
    destacada: false,
  },
  {
    id: 24,
    nombre: "Kadabra",
    tipo: "psiquico",
    precio: 11000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/64.png",
    descripcion: "Emite ondas alfa capaces de provocar dolor de cabeza cerca suyo.",
    stock: 10,
    stockCritico: 3,
    destacada: false,
  },
  {
    id: 25,
    nombre: "Gastly",
    tipo: "psiquico",
    precio: 6000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png",
    descripcion: "Casi todo su cuerpo es gas. Se desvanece con el viento fuerte.",
    stock: 14,
    stockCritico: 4,
    destacada: false,
  },
  {
    id: 26,
    nombre: "Mewtwo",
    tipo: "psiquico",
    precio: 30000,
    precioAnterior: 37500,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png",
    descripcion: "Creado con ingeniería genética. Considerado el Pokémon más poderoso.",
    stock: 3,
    stockCritico: 1,
    destacada: true,
  },
  {
    id: 27,
    nombre: "Mew",
    tipo: "psiquico",
    precio: 55000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png",
    descripcion: "Un Pokémon mítico y muy escaso. Contiene el código genético de todos los demás.",
    stock: 2,
    stockCritico: 1,
    destacada: true,
  },

  // ---------- NORMAL ----------
  {
    id: 28,
    nombre: "Pidgey",
    tipo: "normal",
    precio: 4000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png",
    descripcion: "Muy común en bosques y praderas. Aletea cerca del suelo para levantar arena.",
    stock: 20,
    stockCritico: 6,
    destacada: false,
  },
  {
    id: 29,
    nombre: "Rattata",
    tipo: "normal",
    precio: 4000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png",
    descripcion: "Sus bigotes son un radar sensible al viento y a la temperatura.",
    stock: 22,
    stockCritico: 6,
    destacada: false,
  },
  {
    id: 30,
    nombre: "Eevee",
    tipo: "normal",
    precio: 16000,
    precioAnterior: 19000,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png",
    descripcion: "Su composición genética inestable le permite evolucionar en varias formas.",
    stock: 8,
    stockCritico: 3,
    destacada: true,
  },
  {
    id: 31,
    nombre: "Snorlax",
    tipo: "normal",
    precio: 26000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png",
    descripcion: "Come 400 kg al día y luego se queda dormido donde sea.",
    stock: 6,
    stockCritico: 2,
    destacada: false,
  },
  {
    id: 32,
    nombre: "Dragonite",
    tipo: "normal",
    precio: 56091,
    precioAnterior: 65990,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png",
    descripcion: "Puede volar alrededor del mundo en solo 16 horas. Muy buscada por coleccionistas.",
    stock: 4,
    stockCritico: 2,
    destacada: true,
  },

  // ---------- LUCHA ----------
  {
    id: 33,
    nombre: "Mankey",
    tipo: "lucha",
    precio: 5000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/56.png",
    descripcion: "De temperamento corto. Se enoja por cosas que a otros Pokémon no les afectan.",
    stock: 15,
    stockCritico: 4,
    destacada: false,
  },
  {
    id: 34,
    nombre: "Machop",
    tipo: "lucha",
    precio: 5000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png",
    descripcion: "Entrena todos los días levantando cosas cada vez más pesadas.",
    stock: 14,
    stockCritico: 4,
    destacada: false,
  },
  {
    id: 35,
    nombre: "Hitmonchan",
    tipo: "lucha",
    precio: 12000,
    precioAnterior: 0,
    imagen: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/107.png",
    descripcion: "Lanza combinaciones de golpes tan rápido que parecen un solo puñetazo.",
    stock: 9,
    stockCritico: 3,
    destacada: false,
  },
];

/**
 * Busca un producto por su id. Devuelve undefined si no existe.
 */
function buscarProductoPorId(id) {
  return productos.find((producto) => producto.id === id);
}

/**
 * Da formato de precio en pesos chilenos (ej: 15000 -> "$15.000").
 */
function formatearPrecio(numero) {
  return "$" + numero.toLocaleString("es-CL");
}
